---
# - name: Set up parameters.yml for app.
#   template:
#     src: "{{ playbook_dir }}/templates/parameters.yml.dist"
#     dest: "{{ ansistrano_release_path.stdout }}/app/config/parameters.yml"

# This project does not have migrations.
#- name: Run migrations
#  command: '{{ release_console_path }} doctrine:migrations:migrate --no-interaction'
#  register: run_migrations_output
#  changed_when: not run_migrations_output.stdout|search('No migrations to execute')
#  run_once: True
